/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System health + per-series freshness
         * @description Returns the overall health status and a list of all 25 series with their current freshness state (fresh | stale | failed) and the timestamp of the last successful extraction. The frontend sidebar uses this to display the sync indicator.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all economic indicator series
         * @description Returns all 25 configured series with their metadata and current extraction status. Optionally filter by category (e.g. 'Inflação', 'Juros', 'Câmbio', 'Mercado', 'Atividade', 'Trabalho', 'Fiscal', 'Externo').
         */
        get: operations["list_series_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get single series metadata
         * @description Returns full metadata for one economic indicator series, including source information, frequency, unit, and current extraction status. Used by the Metadados dossier page.
         */
        get: operations["get_series_series__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{code}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get raw observations for a series
         * @description Returns stored time-series observations for the given series. Supports optional date range filtering via `from` and `to` (ISO-8601). Results are ordered by observed_at ascending. Maximum 5000 rows returned per request (default 500). Decimal values stored in Postgres are returned as float64.
         */
        get: operations["get_observations_series__code__observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{code}/transform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a transform to a series
         * @description Applies the requested statistical transform to all stored observations for the series. Results are cached in Redis (TTL: daily=1h, monthly=24h, quarterly=7d). Cache key includes the transform spec hash and the latest observed_at timestamp, so new observations automatically invalidate the cache. NaN positions produced by the transform are reported in `metadata.gaps`. Decimal DB values are returned as float64.
         */
        post: operations["apply_transform_series__code__transform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List release calendar events
         * @description Returns scheduled and realized release events for economic indicators. Filter by `month` (YYYY-MM format) and/or `category` (pt-BR category name). Daily-frequency series are excluded from the calendar per FR-6.7. Events with scheduled_for in the past will have status='realized'; future events will have status='expected'.
         */
        get: operations["list_releases_releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user_prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user preferences
         * @description Returns the current user preferences including pinned series, per-card transform specs, and recently viewed series codes. In single-user v1, always returns the default user row (id=1). Returns an empty state (no pins, no transforms, empty recents) on first call.
         */
        get: operations["get_user_prefs_user_prefs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user preferences (partial)
         * @description Partial update of user preferences. All body fields are optional — omitting a field leaves it unchanged.
         *
         *     **Pin management:** Use `add_pins` and `remove_pins` lists. add_pins is idempotent (already-pinned series are ignored). Removing a pin also removes its card_transform.
         *
         *     **card_transforms:** Map of series_code → TransformSpec dict. Set value to null to remove the transform and revert to 'level'. Only listed series_codes are updated.
         *
         *     **recents:** Full replacement list (max 3 entries kept).
         *
         *     Returns the complete updated UserPrefsRead after applying all changes.
         */
        patch: operations["update_user_prefs_user_prefs_patch"];
        trace?: never;
    };
    "/admin/extract/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually trigger extraction for a series
         * @description Triggers an immediate extraction run for the given series code. Incremental: fetches since last_success_at if set, else full backfill. Returns outcome with count of inserted/updated observations. LIVE NETWORK CALL — runs against real upstream APIs.
         */
        post: operations["trigger_extraction_admin_extract__code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger backfill for all (or selected) series
         * @description Runs ExtractionService for every series (or the filtered subset). Bounded concurrency = 3 to keep upstream APIs happy. Each series fails independently — one upstream failure does not abort the batch. Returns per-series outcome list. LIVE NETWORK CALL.
         */
        post: operations["trigger_backfill_admin_backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the release calendar from IBGE + BCB scrapers
         * @description Triggers a fresh scrape of IBGE + BCB calendars, merges with hardcoded fallback, and upserts records into the releases table. Scraper failures fall back to hardcoded entries for the same series. LIVE NETWORK CALL — HTML scraping may take ~10-30s.
         */
        post: operations["refresh_calendar_admin_refresh_calendar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BackfillItemResult
         * @description Per-series result inside BackfillResult.
         */
        BackfillItemResult: {
            /**
             * Code
             * @description Series code.
             */
            code: string;
            /**
             * Status
             * @description 'success' | 'failed'.
             */
            status: string;
            /**
             * Observations Upserted
             * @description Rows inserted/updated.
             */
            observations_upserted: number;
            /**
             * Error
             * @description Failure detail.
             */
            error?: string | null;
        };
        /**
         * BackfillResult
         * @description Response schema for POST /admin/backfill.
         */
        BackfillResult: {
            /**
             * Total
             * @description Total series attempted.
             */
            total: number;
            /**
             * Success
             * @description Number of series that completed successfully.
             */
            success: number;
            /**
             * Failed
             * @description Number of series that failed.
             */
            failed: number;
            /**
             * Items
             * @description Per-series outcome list.
             */
            items?: components["schemas"]["BackfillItemResult"][];
            /**
             * Started At
             * Format: date-time
             * @description UTC timestamp when backfill began.
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             * @description UTC timestamp when backfill ended.
             */
            finished_at: string;
        };
        /**
         * CalendarRefreshResult
         * @description Response schema for POST /admin/refresh-calendar.
         */
        CalendarRefreshResult: {
            /**
             * Upserted
             * @description Number of release rows inserted/updated.
             */
            upserted: number;
            /**
             * Scraped Count
             * @description Records returned by scrapers.
             */
            scraped_count: number;
            /**
             * Hardcoded Count
             * @description Records returned by hardcoded fallback.
             */
            hardcoded_count: number;
            /**
             * Skipped Daily
             * @description Daily-series records filtered out.
             */
            skipped_daily: number;
            /**
             * Sources
             * @description Per-source breakdown.
             */
            sources?: components["schemas"]["CalendarRefreshSource"][];
            /**
             * Refreshed At
             * Format: date-time
             * @description UTC timestamp when this refresh ran.
             */
            refreshed_at: string;
        };
        /**
         * CalendarRefreshSource
         * @description Per-source result inside CalendarRefreshResult.
         */
        CalendarRefreshSource: {
            /**
             * Source
             * @description Source name: 'ibge' | 'bcb' | 'hardcoded'.
             */
            source: string;
            /**
             * Status
             * @description 'ok' | 'failed'.
             */
            status: string;
            /**
             * Count
             * @description Records produced by this source.
             */
            count: number;
            /**
             * Error
             * @description Error message on failure.
             */
            error?: string | null;
        };
        /**
         * CardTransformRead
         * @description Active transform spec for a pinned Painel card.
         */
        CardTransformRead: {
            /**
             * Series Code
             * @description Series code this transform applies to.
             */
            series_code: string;
            /**
             * Transform Spec
             * @description TransformSpec dict, e.g. {"op": "yoy", "params": {}}.
             */
            transform_spec: Record<string, never>;
        };
        /**
         * ExtractionResultResponse
         * @description Response schema for POST /admin/extract/{code}.
         *
         *     Reports the outcome of a manual extraction trigger.
         */
        ExtractionResultResponse: {
            /**
             * Series Code
             * @description Series code that was extracted.
             */
            series_code: string;
            /**
             * Status
             * @description Outcome: 'success' | 'failed'. Mirrors series.status after the run.
             */
            status: string;
            /**
             * Observations Upserted
             * @description Number of observation rows inserted or updated.
             */
            observations_upserted: number;
            /**
             * Latest Observed At
             * @description Timestamp of the most recent observation after this extraction. Null on failure.
             */
            latest_observed_at?: string | null;
            /**
             * Extraction At
             * Format: date-time
             * @description UTC timestamp when the extraction was triggered.
             */
            extraction_at: string;
            /**
             * Error
             * @description Error message if the extraction failed. Null on success.
             */
            error?: string | null;
        };
        /**
         * GapRecord
         * @description A single NaN gap detected in a transformed series.
         */
        GapRecord: {
            /**
             * Date
             * @description ISO-8601 date string (YYYY-MM-DD) of the gap.
             */
            date: string;
            /**
             * Reason
             * @description Reason for the gap. Currently always 'missing_upstream'.
             * @default missing_upstream
             */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response schema for GET /health.
         *
         *     Summarises overall system health and per-series freshness.
         */
        HealthResponse: {
            /**
             * Status
             * @description Aggregate status: 'ok' if all series are fresh, 'degraded' otherwise.
             */
            status: string;
            /**
             * Series
             * @description Per-series freshness list ordered by category then code.
             */
            series?: components["schemas"]["SeriesFreshness"][];
            /**
             * Checked At
             * Format: date-time
             * @description UTC timestamp when this health check was computed.
             */
            checked_at: string;
            /**
             * Sync At
             * @description Oldest 'last_success_at' across series — represents minimum sync freshness. Null if any series never extracted.
             */
            sync_at?: string | null;
        };
        /**
         * ObservationListResponse
         * @description Response schema for GET /series/{code}/observations.
         */
        ObservationListResponse: {
            /**
             * Series Code
             * @description Series code these observations belong to.
             */
            series_code: string;
            /**
             * Items
             * @description Observations ordered by observed_at ascending.
             */
            items: components["schemas"]["ObservationRead"][];
            /**
             * Total
             * @description Total rows matching the query before limit was applied.
             */
            total: number;
            /**
             * Returned
             * @description Number of rows in this response.
             */
            returned: number;
            /**
             * Limit
             * @description Effective limit applied (max 5000, default 500).
             */
            limit: number;
            /**
             * From Dt
             * @description Lower bound applied (inclusive), if provided.
             */
            from_dt?: string | null;
            /**
             * To Dt
             * @description Upper bound applied (inclusive), if provided.
             */
            to_dt?: string | null;
        };
        /**
         * ObservationRead
         * @description A single time-series data point.
         *
         *     Note: `value` is returned as float (converted from Decimal at the DB
         *     boundary). Precision is preserved to 6 decimal places by the DB schema.
         */
        ObservationRead: {
            /**
             * Observed At
             * Format: date-time
             * @description UTC timestamp of the observation (timezone-aware ISO-8601).
             */
            observed_at: string;
            /**
             * Value
             * @description Numeric value as float64. Source precision: Numeric(20, 6).
             */
            value: number;
            /**
             * Ingested At
             * Format: date-time
             * @description UTC timestamp when this row was first written to the database.
             */
            ingested_at: string;
        };
        /**
         * PinRead
         * @description A pinned series entry.
         */
        PinRead: {
            /**
             * Series Code
             * @description Pinned series code.
             */
            series_code: string;
            /**
             * Order
             * @description Display order in Painel (0-based ascending).
             */
            order: number;
        };
        /**
         * ReleaseListResponse
         * @description Response schema for GET /releases.
         */
        ReleaseListResponse: {
            /**
             * Items
             * @description Release events ordered by scheduled_for ascending.
             */
            items: components["schemas"]["ReleaseRead"][];
            /**
             * Total
             * @description Total number of events returned.
             */
            total: number;
            /**
             * Month
             * @description Month filter applied, if any (YYYY-MM format).
             */
            month?: string | null;
            /**
             * Category
             * @description Category filter applied, if any.
             */
            category?: string | null;
        };
        /**
         * ReleaseRead
         * @description A scheduled or realized release event for an economic indicator.
         *
         *     Daily-frequency series are excluded from releases (FR-6.7).
         */
        ReleaseRead: {
            /**
             * Id
             * @description Surrogate primary key.
             */
            id: number;
            /**
             * Series Code
             * @description Series code this release belongs to.
             */
            series_code: string;
            /**
             * Scheduled For
             * Format: date
             * @description Expected publication date (ISO-8601 date).
             */
            scheduled_for: string;
            /**
             * Status
             * @description 'expected' (future/unconfirmed) | 'realized' (past, confirmed published).
             */
            status: string;
            /**
             * Source Type
             * @description How the date was determined: 'scraped' | 'hardcoded' | 'inferred'.
             */
            source_type: string;
        };
        /**
         * SeriesFreshness
         * @description Freshness record for a single series, returned inside HealthResponse.
         */
        SeriesFreshness: {
            /**
             * Code
             * @description Series code, e.g. 'IPCA'.
             */
            code: string;
            /**
             * Status
             * @description 'fresh' | 'stale' | 'failed'.
             */
            status: string;
            /**
             * Last Success At
             * @description UTC timestamp of last successful extraction. Null if never extracted.
             */
            last_success_at?: string | null;
        };
        /**
         * SeriesListResponse
         * @description Response schema for GET /series.
         */
        SeriesListResponse: {
            /**
             * Items
             * @description List of all series ordered by category then code.
             */
            items: components["schemas"]["SeriesRead"][];
            /**
             * Total
             * @description Total number of series returned.
             */
            total: number;
        };
        /**
         * SeriesRead
         * @description Full metadata for a single economic indicator series.
         *
         *     Numeric values stored as Decimal in Postgres are returned as float here.
         */
        SeriesRead: {
            /**
             * Code
             * @description Series primary key, e.g. 'IPCA'.
             */
            code: string;
            /**
             * Name
             * @description Human-readable display name (pt-BR).
             */
            name: string;
            /**
             * Category
             * @description Grouping category, e.g. 'Inflação', 'Juros'.
             */
            category: string;
            /**
             * Source
             * @description Data source name, e.g. 'BCB SGS', 'IBGE SIDRA'.
             */
            source: string;
            /**
             * Source Id
             * @description Source-system identifier, e.g. '433' for BCB SGS.
             */
            source_id: string;
            /**
             * Frequency
             * @description Release cadence: 'daily' | 'monthly' | 'quarterly' | 'event'.
             */
            frequency: string;
            /**
             * Unit
             * @description Unit of measure, e.g. '%', 'R$', 'pts'.
             */
            unit: string;
            /**
             * First Observation
             * @description Date of the earliest known observation for this series.
             */
            first_observation?: string | null;
            /**
             * Last Extraction At
             * @description UTC timestamp of the most recent extraction attempt.
             */
            last_extraction_at?: string | null;
            /**
             * Last Success At
             * @description UTC timestamp of the most recent successful extraction.
             */
            last_success_at?: string | null;
            /**
             * Status
             * @description Freshness status: 'fresh' | 'stale' | 'failed'.
             */
            status: string;
            /**
             * Next Release At
             * @description Date of the next scheduled release (min scheduled_for >= today). Null if no future release.
             */
            next_release_at?: string | null;
            /**
             * Metadata
             * @description Source-specific metadata (methodology notes, URLs, etc.).
             */
            metadata?: Record<string, never> | null;
        };
        /**
         * TransformMetadata
         * @description Metadata about a transform computation result.
         */
        TransformMetadata: {
            /**
             * Gaps
             * @description List of NaN positions detected after transform. Empty when no gaps.
             */
            gaps?: components["schemas"]["GapRecord"][];
            /**
             * Stub
             * @description True when the op is a stub (sa, calendar_adj) — values are level passthrough.
             * @default false
             */
            stub: boolean;
            /**
             * Op
             * @description Transform operation applied.
             */
            op: string;
            /**
             * Params
             * @description Effective parameters used.
             */
            params?: Record<string, never>;
            /**
             * Cached
             * @description True if the result was served from Redis cache.
             */
            cached: boolean;
            /**
             * Latest Observed At
             * @description ISO-8601 timestamp of the most recent observation used for cache keying.
             */
            latest_observed_at?: string | null;
        };
        /**
         * TransformRequest
         * @description Request body for POST /series/{code}/transform.
         */
        TransformRequest: {
            /**
             * Op
             * @description Transform operation identifier. One of: level, sa, calendar_adj, mom, qoq, yoy, annualized, diff, log_diff, pp, ma, ewma, accum12, stddev12, rebase, zscore, percentile.
             */
            op: string;
            /**
             * Params
             * @description Operation parameters. op-specific keys: ma → {window: int (default 12)}, ewma → {span: int (default 12)}, rebase → {base: float (default 100.0)}. All other ops ignore params.
             */
            params?: Record<string, never>;
        };
        /**
         * TransformResponse
         * @description Response schema for POST /series/{code}/transform.
         */
        TransformResponse: {
            /**
             * Series Code
             * @description Series code the transform was applied to.
             */
            series_code: string;
            /**
             * Values
             * @description Transformed time series ordered by date ascending.
             */
            values: components["schemas"]["TransformValuePoint"][];
            /** @description Computation metadata including gap list. */
            metadata: components["schemas"]["TransformMetadata"];
        };
        /**
         * TransformValuePoint
         * @description A single (date, value) point in a transform result.
         */
        TransformValuePoint: {
            /**
             * Date
             * @description ISO-8601 date string (YYYY-MM-DD).
             */
            date: string;
            /**
             * Value
             * @description Transformed float value. null where the transform produced NaN.
             */
            value: number | null;
        };
        /**
         * UserPrefsRead
         * @description Full user preferences response.
         *
         *     Represents the single-user state including pinned series,
         *     per-card transform specs, and recently viewed series codes.
         */
        UserPrefsRead: {
            /**
             * Id
             * @description Always 1 in single-user v1 deployment.
             */
            id: number;
            /**
             * Pins
             * @description Pinned series ordered by display order.
             */
            pins?: components["schemas"]["PinRead"][];
            /**
             * Card Transforms
             * @description Active transform spec per pinned card. Absent entries default to 'level'.
             */
            card_transforms?: components["schemas"]["CardTransformRead"][];
            /**
             * Recents
             * @description Recently viewed series codes, most recent first (max 3).
             */
            recents?: string[];
            /**
             * Updated At
             * @description UTC timestamp of last modification.
             */
            updated_at?: string | null;
        };
        /**
         * UserPrefsUpdate
         * @description Partial update body for PATCH /user_prefs.
         *
         *     All fields are optional — unset fields are unchanged.
         *
         *     Pins use add/remove lists rather than full replacement to prevent
         *     accidental data loss on concurrent edits.
         *
         *     card_transforms is a mapping from series_code to TransformSpec dict
         *     (or null to remove the transform and revert to level).
         */
        UserPrefsUpdate: {
            /**
             * Add Pins
             * @description Series codes to add to pins (idempotent — already-pinned codes are ignored).
             */
            add_pins?: string[] | null;
            /**
             * Remove Pins
             * @description Series codes to remove from pins. Unpinning also removes the card transform.
             */
            remove_pins?: string[] | null;
            /**
             * Card Transforms
             * @description Map of series_code → TransformSpec dict (or null to remove). Only listed series are updated; others are unchanged.
             */
            card_transforms?: {
                [key: string]: Record<string, never> | null;
            } | null;
            /**
             * Recents
             * @description Full replacement of the recents list (max 3 entries kept).
             */
            recents?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_series_series_get: {
        parameters: {
            query?: {
                /** @description Filter by category name (case-sensitive, pt-BR). Omit to return all. */
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Series list returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_series__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Series metadata returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesRead"];
                };
            };
            /** @description Series code not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observations_series__code__observations_get: {
        parameters: {
            query?: {
                /** @description Start date (inclusive). ISO-8601: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS. */
                from?: string | null;
                /** @description End date (inclusive). ISO-8601: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS. */
                to?: string | null;
                /** @description Maximum rows to return. Default 500, max 5000. */
                limit?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observations returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationListResponse"];
                };
            };
            /** @description Series code not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid date format or limit out of range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apply_transform_series__code__transform_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransformRequest"];
            };
        };
        responses: {
            /** @description Transform applied and result returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransformResponse"];
                };
            };
            /** @description Series code not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid TransformSpec: unknown op or invalid params. See spec for valid op values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transform computation failed (e.g. numeric overflow). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_releases_releases_get: {
        parameters: {
            query?: {
                /** @description Filter by calendar month in YYYY-MM format (e.g. '2026-05'). */
                month?: string | null;
                /** @description Filter by series category (pt-BR). E.g. 'Inflação', 'Juros', 'Câmbio', 'Mercado', 'Atividade', 'Trabalho', 'Fiscal', 'Externo'. */
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release events returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseListResponse"];
                };
            };
            /** @description Invalid month format. Use YYYY-MM. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_prefs_user_prefs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User preferences returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrefsRead"];
                };
            };
        };
    };
    update_user_prefs_user_prefs_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPrefsUpdate"];
            };
        };
        responses: {
            /** @description User preferences updated and returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrefsRead"];
                };
            };
            /** @description One or more series codes in add_pins not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid body shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_extraction_admin_extract__code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extraction completed (check status field for success/failure). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResultResponse"];
                };
            };
            /** @description Series code not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Series source cannot be mapped to a known adapter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_backfill_admin_backfill_post: {
        parameters: {
            query?: {
                /** @description Optional list of series codes. Omit to backfill all 25 series. */
                codes?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_calendar_admin_refresh_calendar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRefreshResult"];
                };
            };
        };
    };
}
